# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/refseq_fastq_downloader',
                'doc_host': 'https://ssi-dk.github.io',
                'git_url': 'https://github.com/ssi-dk/refseq_fastq_downloader',
                'lib_path': 'refseq_fastq_downloader'},
  'syms': {'refseq_fastq_downloader.core': {'refseq_fastq_downloader.core.foo': ('core.html#foo', 'refseq_fastq_downloader/core.py')}}}
